# Generated by Django 3.2.8 on 2021-11-01 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogger',
            new_name='Employee',
        ),
    ]
